### ISSUE TITLE
MCP Integration - Client and Server Capabilities

### ISSUE THREAD

**Issue by e-schultz** [e-schultz/float-ctl#11]
## Context
FLOAT should be able to both query external knowledge sources (MCP client) and expose its capabilities to tools like Claude (MCP server). This enables workflows like:
- Querying OpenMemory/Readwise during processing for related content
- Sending files from Claude directly to FLOAT for processing
- Exposing FLOAT search/query capabilities to external tools

## Vision
Transform FLOAT from a file processor into a knowledge orchestration system that connects multiple knowledge sources.

### Phase 1: Basic MCP Client (#11)
- Query single MCP tool from batch files
- Start with ChromaDB queries (already have client)
- Use mcp-use for rapid prototyping

### Phase 2: Multi-Tool MCP Client (#12)
- Query multiple tools in parallel
- OpenMemory integration
- Readwise integration
- Structure queries in batch YAML

### Phase 3: MCP Server Basics (#13)
- Expose FLOAT as MCP server
- Basic tools: send_files, query, status
- Handle file uploads from Claude

### Phase 4: Advanced MCP Server (#14)
- Create batch files from Claude
- Streaming progress updates
- Advanced query capabilities
- Trigger complex workflows

## Example Batch File with MCP Queries
```yaml
---
uid: abc-123
batchType: "research-synthesis"
externalQueries:
  openMemory:
    search: ["memory palace", "FLOAT architecture"]
  readwise:
    search: ["neurodivergent", "PKM"]
    tags: ["#float", "#memory"]
  chroma:
    collections: ["float_tripartite_v2_concept"]
    query: "memory augmentation"
---
```

## Dependencies
- #8 - Middleware Architecture (everything builds on this)
- #9 - Batch Processing (context for MCP queries)

## Success Criteria
- Can query external knowledge during processing
- Can send files from Claude to FLOAT
- External queries enrich .dis file generation
- Clean middleware implementation

## Future Possibilities
- Two-way sync with external tools
- Automatic knowledge graph building
- Cross-tool knowledge synthesis
