### ISSUE TITLE
Implement Basic Batch Processing with .batch.dis.md Files

### ISSUE THREAD

**Issue by e-schultz** [e-schultz/float-ctl#9]
## Context
Following discussion about git workflow improvements and contextual file processing. The concept is that files can have different meanings depending on their processing context - the same file included in different batches might be summarized differently based on why it's being included.

## Objective
Implement support for .batch.dis.md files that describe groups of related files to process together with shared context.

## Batch File Format
```yaml
---
uid: [generated-uuid]
process: true|false          # Manual processing control
processed: true|false        # Processing status
processHistory: []           # Array of processing timestamps
batchType: string           # Type of batch for specialized processing
domain: string              # Tripartite domain hint
---

# Batch Description
This is a collection of chat logs and research papers about memory systems.

## Files
- file1.md
    - My conversation with Claude about memory palaces
- file2.pdf
    - Research paper on spatial memory [connectsTo:: memory-concepts]
- file3.md
    - Daily log with implementation notes
```

## Tasks
- [ ] Create BatchContextMiddleware (depends on #8)
- [ ] Add batch file parsing logic
- [ ] Support file lists with optional descriptions
- [ ] Pass batch context to other middlewares via ProcessingContext
- [ ] Update .dis generation to include batch context
- [ ] Add floatctl batch commands:
  - [ ] `floatctl batch create <name>` - Generate new batch manifest
  - [ ] `floatctl batch process <name>` - Process specific batch
  - [ ] `floatctl batch status` - Show pending batches
- [ ] Update git hook to detect .batch.dis.md files
- [ ] Add tests for batch processing
- [ ] Document batch file format in README

## Testing Approach
- Create sample .batch.dis.md files
- Verify files are processed with batch context
- Ensure .dis files reference the batch they came from
- Test git hook integration

## Dependencies
- #8 - Middleware Architecture (must be completed first)

## Future Enhancements
- Vault file references (e.g., FLOAT.logs/2025-06-20.md)
- External queries via MCP tools
- JSONLogic queries for dynamic file inclusion
- In-memory ChromaDB for batch-specific context
